# Generated by Django 4.1.4 on 2022-12-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
