# Generated by Django 4.1.4 on 2023-01-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0002_alter_customer_email_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
