# Generated by Django 4.1.4 on 2023-01-09 05:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0003_alter_customer_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_uid', models.UUIDField(default=uuid.uuid4)),
                ('turf_name', models.CharField(max_length=200, null=True)),
                ('turf_address', models.CharField(max_length=200, null=True)),
                ('turf_phone', models.IntegerField(max_length=200, null=True)),
                ('turf_email', models.EmailField(max_length=200, null=True)),
                ('cost_per_hr', models.IntegerField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200)),
                ('turf_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
