# Generated by Django 4.1.4 on 2023-01-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0007_customer_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='turf_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
