# Generated by Django 4.1.4 on 2023-02-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0011_rename_in_time_booking_turf_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
