# Generated by Django 4.1.4 on 2023-02-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0012_remove_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
