# Generated by Django 4.1.4 on 2023-02-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0013_delete_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='datetime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
