# Generated by Django 4.1.4 on 2023-02-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0014_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='t_and_d',
            field=models.DateField(),
        ),
    ]
