# Generated by Django 4.1.4 on 2023-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0017_alter_booking_t_and_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_id', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timeslots', models.CharField(choices=[('09:00 - 10:00 A.M', '09:00 - 10:00 A.M'), ('10:00 - 11:00 A.M', '10:00 - 11:00 A.M'), ('11:00 - 12:00 A.M', '11:00 - 12:00 A.M')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
