# Generated by Django 4.1.4 on 2023-02-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0018_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='timeslots',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sportzify.tag'),
        ),
    ]
