# Generated by Django 4.1.4 on 2023-02-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0019_tag_remove_timeslot_timeslots_timeslot_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='ground_type',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Batminton', 'Batminton'), ('Hockey', 'Hockey')], default='Select Ground Type', max_length=20),
        ),
    ]
