# Generated by Django 4.1.4 on 2023-02-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0020_turf_ground_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='turf_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='turf_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportzify.turf'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportzify.customer'),
        ),
        migrations.AlterField(
            model_name='turf',
            name='ground_type',
            field=models.CharField(choices=[('--Select Ground Type--', '--Select Ground Type--'), ('Cricket', 'Cricket'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Batminton', 'Batminton'), ('Hockey', 'Hockey')], default='Select Ground Type', max_length=50),
        ),
    ]
