# Generated by Django 4.1.4 on 2023-02-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0021_remove_booking_turf_id_booking_turf_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_uid',
        ),
    ]
