# Generated by Django 4.1.4 on 2023-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0022_remove_booking_booking_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='price',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='tags',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
