# Generated by Django 4.1.4 on 2023-02-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0023_remove_timeslot_price_remove_timeslot_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='turf_id',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='turf_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportzify.turf'),
        ),
    ]
