# Generated by Django 4.1.4 on 2023-02-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0024_remove_timeslot_turf_id_timeslot_turf_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='is_available',
        ),
    ]
