# Generated by Django 4.1.4 on 2023-03-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0025_remove_timeslot_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
