# Generated by Django 4.1.4 on 2023-03-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0026_alter_turf_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
