# Generated by Django 4.1.4 on 2023-03-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0030_alter_review_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewRating',
        ),
    ]
