# Generated by Django 4.1.4 on 2023-03-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0033_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
