# Generated by Django 4.1.4 on 2023-03-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0034_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_count', models.CharField(max_length=200, null=True)),
                ('t_and_d', models.CharField(max_length=100, null=True)),
                ('time_slot', models.CharField(max_length=50, null=True)),
                ('datetime', models.CharField(max_length=100, null=True)),
                ('turf_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportzify.turf')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportzify.customer')),
            ],
        ),
    ]
