# Generated by Django 4.1.4 on 2023-03-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0035_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='updated_at',
        ),
    ]
