# Generated by Django 4.1.4 on 2023-03-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0037_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='review',
            new_name='reviews',
        ),
    ]
