# Generated by Django 4.1.4 on 2023-04-19 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzify', '0040_remove_booking_datetime_booking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 14, 48, 39, 287840)),
        ),
    ]
